exclude: beka/.*|.pre-commit-config.yaml|\.git_backup|READ.me
repos:
- hooks:
  - args:
    - --multiline
    - --negate
    entry: '^(chore|test|feat|fix|build|docs|refactor)!?(\([a-z]+\))?: [a-z].*'
    id: commit-msg
    language: pygrep
    name: conventional commit messages
    stages:
    - commit-msg
  repo: local
- hooks:
  - args:
    - --safe
    id: black
  repo: https://github.com/psf/black
  rev: 23.9.1
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: debug-statements
    language_version: python3
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
- hooks:
  - id: flake8
    language_version: python3
  repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
- hooks:
  - args:
    - --application-directories=.:src --py36-plus
    id: reorder-python-imports
  repo: https://github.com/asottile/reorder_python_imports
  rev: v2.6.0
- hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v3.30.0
