repos:
-   repo: local
    hooks:
    -   id: commit-msg
        name: conventional commit messages
        language: pygrep
        entry: '^(chore|test|feat|fix|build|docs|refactor)!?(\([a-z]+\))?: [a-z].*'
        args:
        - --multiline
        - --negate # This fails the commit if the entry is NOT matched
        stages:
        - commit-msg

-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    -   id: black
        args: [--safe]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: debug-statements
        language_version: python3

-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        language_version: python3

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
    -   id: reorder-python-imports
        args: [--application-directories=.:src --py36-plus]
          
exclude: 'bekavenv/.*|.pre-commit-config.yaml|\.git_backup'
